package dto

import (
	"time"

	"github.com/SscSPs/money_managemet_app/internal/models"
)

// CreateUserRequest defines the data needed to create a new user.
// Assuming UserID is generated by the system or passed separately.
type CreateUserRequest struct {
	Name string `json:"name" binding:"required"`
	// Add other fields like email, password hash etc. if needed later
}

// UserResponse defines the data returned for a user.
type UserResponse struct {
	UserID        string    `json:"userID"`
	Name          string    `json:"name"`
	CreatedAt     time.Time `json:"createdAt"`
	CreatedBy     string    `json:"createdBy"`
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	LastUpdatedBy string    `json:"lastUpdatedBy"`
	// Add other fields if needed later
}

// ToUserResponse converts a models.User to UserResponse DTO
func ToUserResponse(user *models.User) UserResponse {
	return UserResponse{
		UserID:        user.UserID,
		Name:          user.Name,
		CreatedAt:     user.CreatedAt,
		CreatedBy:     user.CreatedBy,
		LastUpdatedAt: user.LastUpdatedAt,
		LastUpdatedBy: user.LastUpdatedBy,
	}
}
